export enum SQLErrors {
  DUPLICATE_REGISTER =  'ER_DUP_ENTRY',
  ERROR_DB_CONNECT = 'ECONNREFUSED',
  GENERIC_DB_ERROR = 'GENERIC_DB_ERROR',
  NOT_FOUND_REGISTER = 'NOT_FOUND_REGISTER'
}

export enum ProvidersErrors {
    ALREADY_EXISTS_WISHLIST = 'ALREADY_EXISTS_WISHLIST'
}